'use client';
import React,{useState,useEffect,useRef,useMemo} from 'react';
import {Droplets,Plus,FileDown,Users,Building2,Package,FlaskConical,Check,ChevronLeft,Trash2,Pencil,BookOpen,ClipboardList,Info,Download,Upload,Calculator,ShieldCheck,AlertTriangle,RefreshCw,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Command,CommandInput,CommandList,CommandEmpty,CommandItem} from '@/components/ui/command';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {DRUGS,emptyWard,newOrder,calculate,summarize,number,fmt,uid,type Ward,type Order,type Patient,type Drug} from '@/lib/model';
import {wardSchema} from '@/lib/validation';
import {makeReport,download} from '@/lib/pdf';
import {loadWard,saveWard,exportNativeFile} from '@/lib/device';
const initial:Ward={schema:1,title:'NICU Ward',date:'',rooms:[]};
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select dir="ltr" value={value} onValueChange={onChange}><SelectTrigger className="pick" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Numeric({label,value,onChange,unit,id}:{label:string;value:string;onChange:(s:string)=>void;unit?:string;id:string}){return <label className="field" htmlFor={id}><span>{label}</span><div className="number-field"><input id={id} dir="ltr" inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} autoComplete="off" placeholder="0"/><bdi>{unit}</bdi></div></label>;}
function Result({order,compact=false}:{order:Order;compact?:boolean}){const c=calculate(order);if(!c.ok)return <div className="result-empty"><Calculator size={28}/><b>Preparation result</b>{order.dose?c.errors.map(e=><p className="error-text" key={e}>{e}</p>):<p>Enter the prescribed single dose to calculate the withdrawal and diluent volumes.</p>}</div>;return <div className={'result '+(compact?'compact':'')} aria-live="polite"><div className="result-heading"><span>Calculated preparation</span><span className={'tag '+(order.verified?'good':'')}>{order.verified?'Reviewed':'Draft calculation'}</span></div>{c.batches.map((b,i)=><div className="batch" key={i}><div className="batch-title">Microdrip {i+1}<span>{b.doses} dose(s) · factor <bdi>{fmt(b.factor)}</bdi></span></div><div className="draw-number"><strong dir="ltr">{fmt(b.draw)}</strong><bdi>mL</bdi></div><div className="draw-label">Withdraw from {order.sourceContainer?'intermediate stock':'vial / ampoule'}</div><div className="result-lines"><p><span>Add <bdi>{order.diluent}</bdi></span><bdi>{fmt(b.diluent)} mL</bdi></p><p><span>Final volume</span><bdi>{fmt(b.finalMl)} mL</bdi></p><p><span>Volume given per dose</span><bdi>{order.doseMl} mL</bdi></p></div></div>)}<div className="result-foot"><b>{c.adminSets+c.sourceSets} microdrip(s)</b><span>{c.adminSets} administration + {c.sourceSets} stock</span><b>{c.vials} new vial(s) / ampoule(s)</b></div>{!compact&&<><p className="fine">Prescribed amount: <bdi>{fmt(c.doseTotal)} {order.unit}</bdi><br/>Dead-space allowance: <bdi>{fmt(c.deadAmount)} {order.unit}</bdi> — not an extra patient dose.</p>{c.warnings.map(w=><p className="small-warning" key={w}>{w}</p>)}</>}</div>;}
function DrugPicker({drug,onChange}:{drug:Drug;onChange:(d:Drug)=>void}){const [open,setOpen]=useState(false);return <Popover modal open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" id="drug-choice" className="drug-picker" role="combobox" aria-label="Drug and vial strength" aria-expanded={open}><span dir="auto">{drug.label}</span><Search size={17}/></button></PopoverTrigger><PopoverContent className="drug-popup" dir="ltr"><Command><CommandInput placeholder="Search drugs…"/><CommandList><CommandEmpty>No match. Search for Other drug.</CommandEmpty>{DRUGS.map(d=><CommandItem key={d.id} value={d.label+' '+d.name} onSelect={()=>{onChange(d);setOpen(false);}}><span dir="auto">{d.label}</span>{drug.id===d.id&&<Check size={15}/>}</CommandItem>)}</CommandList></Command></PopoverContent></Popover>;}
function OrderEditor({patient,existing,onSave,onClose,quick=false}:{patient?:Patient;existing?:Order;onSave:(o:Order)=>void;onClose:()=>void;quick?:boolean}){
 const [o,setO]=useState<Order>(()=>existing??newOrder());const drug=DRUGS.find(d=>d.id===o.drugId)!;const c=calculate(o);
 function change(p:Partial<Order>){setO(old=>({...old,...p,verified:false}));}
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="order-dialog" dir="ltr"><div className="dialog-top"><div><p className="eyebrow">{quick?'Based on the supplied calculation method':patient?.name}</p><DialogTitle>{quick?'Quick preparation calculator':existing?'Edit medication':'Add medication'}</DialogTitle><DialogDescription>Enter the prescribed single dose in its stated unit, not mg/kg.</DialogDescription></div></div><form onSubmit={e=>{e.preventDefault();onSave(o);}} className="editor-grid"><div className="editor-fields"><div className="field"><label htmlFor="drug-choice">Drug and vial strength</label><DrugPicker drug={drug} onChange={d=>setO({...newOrder(d.id),id:o.id,daily:o.daily,perContainer:d.separate?1:o.daily,dose:'',doseMl:o.doseMl,deadMl:o.deadMl})}/></div>
 {drug.custom&&<div className="two-col"><label className="field"><span>Drug name / salt</span><input value={o.name} maxLength={120} onChange={e=>change({name:e.target.value})}/></label><label className="field"><span>Dose and vial unit</span><input dir="ltr" value={o.unit} maxLength={40} onChange={e=>change({unit:e.target.value})} placeholder="mg / mEq / IU"/></label></div>}
 <div className="two-col"><Numeric label="Prescribed single dose" value={o.dose} onChange={v=>change({dose:v})} unit={o.unit} id="dose"/><div className="field"><span>Doses per day</span><Pick label="Doses per day" value={String(o.daily)} onChange={v=>change({daily:+v,perContainer:drug.separate?1:+v})} options={[{value:'1',label:'Once daily · q24h'},{value:'2',label:'Twice daily · q12h'},{value:'3',label:'Three times daily · q8h'}]}/></div></div>
 <div className="section-label">Doses and fluid volumes</div><div className="two-col"><div className="field"><span>Doses per microdrip</span><Pick label="Doses per microdrip" value={String(o.perContainer)} onChange={v=>change({perContainer:+v})} options={(drug.separate?[1]:Array.from({length:o.daily},(_,i)=>i+1)).map(n=>({value:String(n),label:n===1?'One dose':n===2?'Two doses':'Three doses'}))}/></div><div className="field"><span>Administration volume</span><Pick label="Volume preset" value={o.doseMl==='20'?'20':o.doseMl==='10'?'10':'custom'} onChange={v=>change({doseMl:v==='custom'?'':v})} options={[{value:'20',label:'20 mL · standard method'},{value:'10',label:'10 mL · fluid-restricted method'},{value:'custom',label:'Custom approved volume'}]}/></div></div>
 <div className="two-col"><Numeric label="Volume per dose" value={o.doseMl} onChange={v=>change({doseMl:v})} unit="mL" id="dose-volume"/><Numeric label="Actual device dead space" value={o.deadMl} onChange={v=>change({deadMl:v})} unit="mL" id="dead-volume"/></div>
 <div className="source-box"><div className="section-label"><FlaskConical size={17}/> Withdrawal stock</div><div className="two-col"><Numeric label="Drug amount per vial" value={o.amount} onChange={v=>change({amount:v})} unit={o.unit} id="vial-amount"/><Numeric label="Final stock volume" value={o.sourceMl} onChange={v=>change({sourceMl:v})} unit="mL" id="source-volume"/></div><p>Stock concentration: <strong dir="ltr">{fmt(number(o.amount)/number(o.sourceMl))} {o.unit}/mL</strong></p><p className="fine">Use the final reconstituted or intermediate stock volume, not just the diluent added.</p></div>
 <div className="field"><span>Administration diluent</span><Pick label="Administration diluent" value={o.diluent} onChange={v=>change({diluent:v})} options={[{value:'N/S 0.9%',label:'N/S 0.9% · normal saline'},{value:'D5W',label:'D5W · dextrose 5%'}]}/></div>
 <label className="check-row"><Checkbox checked={o.sourceContainer} onCheckedChange={v=>change({sourceContainer:v===true})}/><span>Use an extra microdrip to prepare intermediate stock <small>One stock container per new vial, added to the supply count.</small></span></label>
 <div className={'drug-note '+(drug.blocked?'red':'')}><Info size={18}/><div><b>Source images · page {drug.page}</b><p>{drug.note}</p></div></div>
 <label className="field"><span>Preparation note / stability reference</span><textarea value={o.note} maxLength={600} rows={2} placeholder="Product, preparation time or special instructions…" onChange={e=>change({note:e.target.value})}/></label>
 <label className="check-row review"><Checkbox checked={o.verified} disabled={!c.ok} onCheckedChange={v=>setO(old=>({...old,verified:v===true}))}/><span>I checked the stock, dose unit, dead space and stability against the product label and ward protocol.</span></label>
 <div className="editor-actions"><button type="submit" className="btn primary" disabled={!c.ok}>{quick?'Close calculator':existing?'Save changes':'Add medication'}</button><button type="button" className="btn" onClick={onClose}>Cancel</button></div></div><aside className="result-side"><Result order={o}/><p className="fine">Each microdrip is for one medication and one patient. This calculator does not prescribe a dose or infusion rate.</p></aside></form></DialogContent></Dialog>;
}
export default function WardApp(){
 const [ward,setWard]=useState<Ward>(initial),[loaded,setLoaded]=useState(false),[mode,setMode]=useState('loading'),[selected,setSelected]=useState(''),[tab,setTab]=useState('ward');
 const [editor,setEditor]=useState<{patient?:Patient;order?:Order;quick?:boolean}|null>(null),[entry,setEntry]=useState<{type:'room'|'patient';id?:string;name:string;bed:string}|null>(null),[confirm,setConfirm]=useState<{title:string;text:string;action:()=>void}|null>(null),[pdfBusy,setPdfBusy]=useState(false),[refQuery,setRefQuery]=useState('');
 const [pdfReady,setPdfReady]=useState<{url:string;name:string}|null>(null);
 useEffect(()=>()=>{if(pdfReady)URL.revokeObjectURL(pdfReady.url);},[pdfReady]);
 const revision=useRef(0),loadedRef=useRef(false),modeRef=useRef('loading'),wardRef=useRef(ward),pending=useRef<Ward|null>(null),saving=useRef(false),fileInput=useRef<HTMLInputElement>(null);wardRef.current=ward;modeRef.current=mode;
 const sum=useMemo(()=>summarize(ward),[ward]),room=ward.rooms.find(r=>r.id===selected)??ward.rooms[0];
 async function load(){setMode('loading');try{const raw=loadWard();const next=raw?wardSchema.parse(JSON.parse(raw)):emptyWard();setWard(next);setSelected(next.rooms[0]?.id??'');loadedRef.current=true;setLoaded(true);setMode('saved');}catch{setMode('loaderror');}}
 useEffect(()=>{void load();},[]);
 async function persist(snapshot:Ward){try{saveWard(snapshot);setMode('saved');}catch{setMode('error');}}
 useEffect(()=>{if(loaded)void persist(ward);},[ward,loaded]);
 useEffect(()=>{const onExport=(event:Event)=>{const state=(event as CustomEvent).detail;if(state==='saved')toast.success('File saved');else if(state==='error')toast.error('Could not save the file. Please try again.');};window.addEventListener('native-export',onExport);return()=>window.removeEventListener('native-export',onExport);},[]);
 function updateRoom(fn:(r:Ward['rooms'][number])=>Ward['rooms'][number]){setWard(w=>({...w,rooms:w.rooms.map(r=>r.id===room?.id?fn(r):r)}));}
 function editPatient(id:string,fn:(p:Patient)=>Patient){updateRoom(r=>({...r,patients:r.patients.map(p=>p.id===id?fn(p):p)}));}
 function saveEntry(){if(!entry?.name.trim())return;if(entry.type==='room'){if(entry.id)setWard(w=>({...w,rooms:w.rooms.map(r=>r.id===entry.id?{...r,name:entry.name.trim()}:r)}));else{const id=uid();setWard(w=>({...w,rooms:[...w.rooms,{id,name:entry.name.trim(),patients:[]}]}));setSelected(id);}}else if(room){if(entry.id)editPatient(entry.id,p=>({...p,name:entry.name.trim(),bed:entry.bed.trim()}));else updateRoom(r=>({...r,patients:[...r.patients,{id:uid(),name:entry.name.trim(),bed:entry.bed.trim(),orders:[]}]}));}setEntry(null);}
 function saveOrder(o:Order){if(editor?.quick){setEditor(null);return;}if(!editor?.patient)return;editPatient(editor.patient.id,p=>({...p,orders:editor.order?p.orders.map(x=>x.id===o.id?o:x):[...p.orders,o]}));setEditor(null);toast.success('Medication updated');}
 async function pdf(){setPdfBusy(true);try{const blob=await makeReport(ward);const name=`NICU_Work_${ward.date}.pdf`;if(!await exportNativeFile(blob,name))setPdfReady({url:URL.createObjectURL(blob),name});}catch(error){console.error('PDF export failed',error);toast.error('Could not create the report. Please try again.');}finally{setPdfBusy(false);}}
 async function backup(){try{const blob=new Blob([JSON.stringify(ward,null,2)],{type:'application/json'}),name=`NICU_Backup_${ward.date}.json`;if(!await exportNativeFile(blob,name))download(blob,name);}catch{toast.error('Could not export the backup.');}}
 async function restore(file:File|undefined){if(!file)return;try{if(file.size>1500000)throw Error();const next=wardSchema.parse(JSON.parse(await file.text()));setConfirm({title:'Restore ward backup?',text:'This replaces the current rooms and patients. Export your current backup first if you need to keep it.',action:()=>{setWard(next);setSelected(next.rooms[0]?.id??'');}});}catch{toast.error('The backup is invalid or exceeds the size limit.');}if(fileInput.current)fileInput.current.value='';}
 const example={...newOrder(),dose:'50'};
 return <div className="app"><Toaster dir="ltr" position="bottom-center" theme="light"/><header className="app-header"><div className="brand"><span className="brand-icon"><Droplets/></span><div><h1>NICU Work</h1><p dir="ltr">NICU WORK</p></div></div><div className="header-actions"><span className="private-mark"><ShieldCheck size={16}/> On-device records</span><button className="btn export" disabled={!sum.orders||pdfBusy} onClick={pdf}><FileDown size={18}/>{pdfBusy?'Creating PDF…':'Ward PDF'}</button></div></header>
 <main className="workspace"><div className="work-heading"><div><p className="eyebrow">DAILY PREPARATION RECORD</p><input aria-label="Ward name" className="ward-title" value={ward.title} maxLength={120} onChange={e=>setWard(w=>({...w,title:e.target.value}))}/><p className="muted">Prescribed doses, preparation volumes and ward supplies.</p></div><div className="date-and-save"><label>Work date<input aria-label="Work date" type="date" value={ward.date} onChange={e=>{if(e.target.value)setWard(w=>({...w,date:e.target.value}));}}/></label><span className={'save-status '+(['error','conflict','loaderror'].includes(mode)?'error-text':'')}>{mode==='saved'?<><Check size={14}/> Saved on device</>:mode==='saving'?'Saving…':mode==='demo'?'Preview only':mode==='loading'?'Loading records…':mode==='conflict'?'Newer version found':mode==='loaderror'?'Could not load records':'Changes not saved'}</span></div></div>
 {['error','loaderror'].includes(mode)&&<div className="storage-banner"><AlertTriangle size={19}/><div>{mode==='loaderror'?'Could not load the saved record. Retry before adding data.':'Changes could not be saved. Export a backup before closing.'}</div><button className="btn small" onClick={()=>mode==='loaderror'?void load():void persist(ward)}>Retry</button></div>}
 <div className="metrics"><div><Building2/><span>Rooms</span><strong>{ward.rooms.length}</strong></div><div><Users/><span>Patients</span><strong>{sum.patients}</strong></div><div className="highlight"><Droplets/><span>Microdrip <small>administration + stock</small></span><strong>{sum.sets}</strong></div><div><Package/><span>Vials / ampoules <small>separate preparations</small></span><strong>{sum.vials}</strong></div></div>
 <Tabs dir="ltr" value={tab} onValueChange={setTab}><div className="toolbar"><TabsList className="main-tabs"><TabsTrigger value="ward"><ClipboardList/>Rooms & patients</TabsTrigger><TabsTrigger value="supplies"><Package/>Supplies</TabsTrigger><TabsTrigger value="reference"><BookOpen/>Reference</TabsTrigger></TabsList><button className="btn quiet" onClick={()=>setEditor({quick:true})}><Calculator size={17}/>Quick calculator</button></div>
 <TabsContent value="ward"><div className="room-strip"><div className="room-pills">{ward.rooms.map((r,i)=><button key={r.id} className={'room-pill '+(room?.id===r.id?'selected':'')} onClick={()=>setSelected(r.id)}><span className="room-index">{String(i+1).padStart(2,'0')}</span>{r.name}<small>{r.patients.length}</small></button>)}</div><button disabled={!loaded} className="btn small" onClick={()=>setEntry({type:'room',name:'',bed:''})}><Plus size={17}/>Add room</button></div>
 {!room?<div className="empty-work"><div className="empty-copy"><span className="empty-icon"><Building2 size={30}/></span><h2>Set up your ward</h2><p>Add a room, then patients and their medications.<br/>All rooms are included in one report.</p><button disabled={!loaded} className="btn primary" onClick={()=>setEntry({type:'room',name:'',bed:''})}><Plus size={18}/>Add your first room</button></div><div className="example-panel"><div className="section-label"><Calculator size={17}/>Worked example from the images</div><h3 dir="ltr">Cefotaxime 50 mg × 3/day</h3><p>Stock 1000 mg / 10 mL · dose volume 20 mL · dead space 10 mL</p><Result order={example} compact/><button className="text-button" onClick={()=>setEditor({quick:true,order:example})}>Try another dose <ChevronLeft size={16}/></button></div></div>:<><div className="room-heading"><div><h2>{room.name}</h2><p>{room.patients.length} patient(s) · {room.patients.reduce((s,p)=>s+p.orders.length,0)} medication(s)</p></div><div className="inline-actions"><button className="icon-btn" aria-label="Rename room" onClick={()=>setEntry({type:'room',id:room.id,name:room.name,bed:''})}><Pencil size={16}/></button><button className="icon-btn danger" aria-label="Delete room" onClick={()=>setConfirm({title:'Delete room?',text:`Delete ${room.name} and all its patients and medications from this record.`,action:()=>setWard(w=>({...w,rooms:w.rooms.filter(r=>r.id!==room.id)}))})}><Trash2 size={16}/></button><button className="btn primary" onClick={()=>setEntry({type:'patient',name:'',bed:''})}><Plus size={18}/>Add patient</button></div></div>{!room.patients.length&&<div className="empty-patients"><Users size={30}/><h3>This room is ready</h3><p>Use the patient name or a bed code.</p></div>}
 <div className="patients">{room.patients.map((p,i)=><section className="patient-card" key={p.id}><div className="patient-heading"><div className="patient-name"><span className="patient-number">{i+1}</span><div><h3>{p.name}</h3><small>{p.bed?'Bed '+p.bed:'No bed assigned'} · {p.orders.length} medication(s)</small></div></div><div className="inline-actions"><button className="icon-btn" aria-label={'Edit '+p.name} onClick={()=>setEntry({type:'patient',id:p.id,name:p.name,bed:p.bed})}><Pencil size={16}/></button><button className="icon-btn danger" aria-label={'Delete '+p.name} onClick={()=>setConfirm({title:'Delete patient?',text:`Delete ${p.name} and their medications from this room.`,action:()=>updateRoom(r=>({...r,patients:r.patients.filter(x=>x.id!==p.id)}))})}><Trash2 size={16}/></button><button className="btn small" onClick={()=>setEditor({patient:p})}><Plus size={16}/>Medication</button></div></div>{!p.orders.length?<button className="empty-order" onClick={()=>setEditor({patient:p})}><Plus size={18}/>Add the first prescribed medication</button>:p.orders.map(o=>{const c=calculate(o);return <div className={'order-row '+(!c.ok?'invalid':'')} key={o.id}><div className="order-name"><b dir="auto">{o.name}</b><span dir="ltr">{o.dose} {o.unit} × {o.daily}/day</span><span className={'tag '+(o.verified?'good':'')}>{!c.ok?'Check settings':o.verified?'Reviewed':'Needs review'}</span></div><div className="order-result">{c.ok?<><span>Withdrawal {c.batches.length>1?'per microdrip':''}</span><strong dir="ltr">{c.batches.map(b=>fmt(b.draw)).join(' / ')} <small>mL</small></strong><small>to {c.batches.map(b=>fmt(b.finalMl)).join(' / ')} mL · {o.diluent}</small></>:<p>{c.errors[0]}</p>}</div><div className="order-counts">{c.ok&&<><b>{c.adminSets+c.sourceSets} microdrip(s)</b><span>{c.vials} new vial(s)</span></>}</div><div className="inline-actions"><button className="icon-btn" aria-label={'Edit '+o.name} onClick={()=>setEditor({patient:p,order:o})}><Pencil size={16}/></button><button className="icon-btn danger" aria-label={'Delete '+o.name} onClick={()=>setConfirm({title:'Delete medication?',text:`Delete ${o.name} from the medications of ${p.name}.`,action:()=>editPatient(p.id,x=>({...x,orders:x.orders.filter(z=>z.id!==o.id)}))})}><Trash2 size={16}/></button></div></div>;})}</section>)}</div></>}
 </TabsContent>
 <TabsContent value="supplies"><section className="section-card"><div className="section-header"><div><h2>Whole-ward supplies</h2><p>All rooms · {ward.date}</p></div><button disabled={!sum.orders||pdfBusy} className="btn primary" onClick={pdf}><FileDown size={18}/>Export PDF</button></div><div className="supply-breakdown"><div><strong>{sum.admin}</strong>Administration sets</div><span>+</span><div><strong>{sum.source}</strong>Intermediate stock sets</div><span>=</span><div className="total"><strong>{sum.sets}</strong>Total microdrips</div></div><div className="info-banner"><Info size={19}/><p>Preparation counts use <b>new vials for each microdrip preparation</b> with unused contents discarded. Do not share single-dose vials between patients. Quantity-equivalent counts are inventory arithmetic only, not permission to pool vials.</p></div>{(sum.invalid>0||sum.unverified>0)&&<div className="notice">{sum.invalid>0&&`${sum.invalid} invalid order(s) excluded from totals. `}{sum.unverified>0&&`${sum.unverified} order(s) awaiting review; totals are provisional.`}</div>}
 {!sum.groups.length?<div className="empty-patients"><Package size={28}/><p>Add medications to see ward supply totals.</p></div>:<Table><TableHeader><TableRow><TableHead>Drug / stock</TableHead><TableHead>Total withdrawal</TableHead><TableHead>Prepared amount</TableHead><TableHead>Vials to prepare</TableHead><TableHead>Quantity equivalent only</TableHead></TableRow></TableHeader><TableBody>{sum.groups.map((g,i)=><TableRow key={i}><TableCell><b dir="auto">{g.name}</b><small dir="ltr">{fmt(g.amount)} {g.unit} / {fmt(g.sourceMl)} mL</small></TableCell><TableCell><bdi>{fmt(g.draw)} mL</bdi></TableCell><TableCell><bdi>{fmt(g.prepared)} {g.unit}</bdi></TableCell><TableCell className="count-cell">{g.vials}</TableCell><TableCell>{g.minimum}</TableCell></TableRow>)}</TableBody></Table>}
 <div className="fluids"><h3>Diluent added to administration sets</h3>{Object.entries(sum.fluid).map(([n,ml])=><div key={n}><span dir="ltr">{n}</span><b dir="ltr">{fmt(ml)} mL</b></div>)}<p className="fine">Excludes reconstitution water and intermediate stock fluids. Different drugs, units and strengths are counted separately.</p></div></section></TabsContent>
 <TabsContent value="reference"><section className="section-card"><div className="section-header"><div><h2>Calculation reference</h2><p>Prescribed single dose × preparation factor ÷ stock concentration</p></div><BookOpen size={27}/></div><div className="formula-box"><p>Factor = doses per microdrip + dead space / volume per dose</p><p>Final volume = doses × volume per dose + dead space</p><p>Diluent to add = final volume − withdrawal volume</p></div><Table><TableHeader><TableRow><TableHead>Doses</TableHead><TableHead>20 mL per dose</TableHead><TableHead>10 mL per dose</TableHead></TableRow></TableHeader><TableBody>{[1,2,3].map(n=><TableRow key={n}><TableCell>{n}</TableCell><TableCell><bdi>×{n+0.5} → {20*n+10} mL</bdi></TableCell><TableCell><bdi>×{n+1} → {10*n+10} mL</bdi></TableCell></TableRow>)}</TableBody></Table><p className="fine">Both columns assume 10 mL of dead space, as in the images. Confirm the actual device volume. Fluid restriction is determined by the clinical team.</p>
 <div className="info-banner"><Info size={19}/><p>Stock and administration concentrations are separate. The image stability periods are not automatic expiry dates. Caffeine uses the same dead-space formula with no wash step. Confirm which glucose solution GW refers to in your protocol.</p></div><label className="reference-search"><Search size={18}/><input aria-label="Search drug reference" value={refQuery} onChange={e=>setRefQuery(e.target.value)} placeholder="Search the drug reference…"/></label><div className="drug-reference">{DRUGS.filter(d=>(d.name+' '+d.label).toLowerCase().includes(refQuery.toLowerCase())).map(d=><details key={d.id}><summary><span dir="auto">{d.label}</span><bdi>{d.amount&&d.volume?`${fmt(d.amount/d.volume)} ${d.unit}/mL`:'Strength required'}</bdi></summary><p>{d.note}</p>{d.blocked&&<p className="error-text">{d.blocked}</p>}<small>Page {d.page} of the supplied images</small></details>)}</div><div className="references"><h3>Primary references</h3><a href="https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=2dc7b3d6-3874-40ac-b8aa-7bcfe2dc0cdf&type=display" target="_self" rel="noreferrer">DailyMed · Vancomycin</a><a href="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5f38c395-0093-4afd-89ec-f96e5dc0934a" target="_self" rel="noreferrer">DailyMed · Caffeine citrate</a><a href="https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=f7be6506-4d20-401e-a0ff-02ad7c33158a" target="_self" rel="noreferrer">DailyMed · AmBisome</a><a href="https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=7ea1db43-40fa-417b-8911-ae98092070a0" target="_self" rel="noreferrer">DailyMed · Ceftriaxone</a><a href="https://www.cdc.gov/injection-safety/hcp/clinical-safety/index.html" target="_self" rel="noreferrer">CDC · Single-dose vials</a><p className="fine">Reference review: 26 September 2026. Follow the actual product label and approved ward protocol.</p></div></section></TabsContent></Tabs>
 <footer className="app-footer"><p>Preparation arithmetic, not prescribing. <span>Full precision internally; up to 4 decimal places displayed.</span></p><div><button className="text-button" onClick={backup} disabled={!loaded}><Download size={16}/>Export backup</button><button className="text-button" disabled={!loaded} onClick={()=>fileInput.current?.click()}><Upload size={16}/>Restore backup</button><input ref={fileInput} type="file" accept=".json,application/json" hidden onChange={e=>void restore(e.target.files?.[0])}/></div></footer></main>
 <Dialog open={!!pdfReady} onOpenChange={open=>{if(!open)setPdfReady(null);}}><DialogContent className="name-dialog" dir="ltr"><DialogTitle>Ward report ready</DialogTitle><DialogDescription>One PDF includes supplies and all rooms and patients. Review the calculations before printing or using the report.</DialogDescription>{pdfReady&&<a className="btn primary wide" href={pdfReady.url} download={pdfReady.name}><FileDown size={18}/>Download PDF</a>}</DialogContent></Dialog>
 {editor&&<OrderEditor patient={editor.patient} existing={editor.order} quick={editor.quick} onSave={saveOrder} onClose={()=>setEditor(null)}/>}
 <Dialog open={!!entry} onOpenChange={open=>{if(!open)setEntry(null);}}><DialogContent className="name-dialog" dir="ltr"><DialogTitle>{entry?.id?'Edit': 'Add'} {entry?.type==='room'?'room':'patient'}</DialogTitle><DialogDescription>{entry?.type==='room'?'Enter the room name used in your ward.':'Enter the patient name or code as it should appear in reports.'}</DialogDescription><form onSubmit={e=>{e.preventDefault();saveEntry();}}><label className="field"><span>{entry?.type==='room'?'Room name':'Patient name / code'}</span><input autoFocus required value={entry?.name??''} maxLength={120} onChange={e=>setEntry(x=>x?{...x,name:e.target.value}:x)} placeholder={entry?.type==='room'?'Example: Room 1':'Patient name or code'}/></label>{entry?.type==='patient'&&<label className="field"><span>Bed number (optional)</span><input value={entry.bed} maxLength={120} onChange={e=>setEntry(x=>x?{...x,bed:e.target.value}:x)}/></label>}<button className="btn primary wide" type="submit">Save</button></form></DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent dir="ltr"><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.text}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm?.action();setConfirm(null);}}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
